POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Prueba desde visual studio"
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "important": "content missing error"
}